# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: my blog
name: Tom Ward
email: contactme@tomjbward.co.uk
header-img: img/default-bg.jpg
description: >
  A technical blog with nothing more than a sparse collection of semi-
  interesting things for geeky folk.
url: "http://www.tomjbward.co.uk" # the base hostname & protocol for your site
twitter_username: wardio
github_username:  tomwardio

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: pretty
paginate: 10
gems: [jekyll-paginate]
exclude: ["node_modules", "CNAME", "Gruntfile.coffee", "package.json", "README.md"]
