title: "Tom Ward"
author: "Tom Ward"
description: "A blog about nothing"
permalink: /blog/:title/
lang: "en"
excerpt_separator: <!--more-->
date_format: "%B %d, %Y"
paginate: 5
paginate_path: "/blog/page:num"

exclude: ["contact/server"]

# Layout
show_excerpts: true         # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false         # show a sidebar instead of the usual header
minimal: false              # use a dark header

# Menu
navigation:
  - {file: "index.html"}
  - {file: "contact.md"}

external:
  - {title: Mail, icon: linkedin, url: "https://www.linkedin.com/in/tomjward"}
  - {title: GitHub, icon: github, url: "https://github.com/tomwardio"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
  disqus: true
  disqus_shortname: "tomjbward"

plugins:
 - jekyll-feed
 - jekyll-paginate
