# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: my blog
name: Tom Ward
email: contactme@tomjbward.co.uk
header-img: img/default-bg.jpg
description: >
  A technical blog by Tom Ward. Nothing more than a sparse collection of semi-
  interesting things for equally geeky folk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.tomjbward.co.uk" # the base hostname & protocol for your site
twitter_username: wardio
github_username:  tomwardio

# Build settings
markdown: redcarpet
permalink: pretty
paginate: 10
gems: [jekyll-paginate]
exclude: ["node_modules"]
